<a href="https://colab.research.google.com/github/HammadN98/Curso_Estatistica/blob/main/S5Medidas_posicao_dispersao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import statistics
from scipy import stats
import math

In [2]:
dados_altura = [150, 151,152,152,153,154,155,155,155,155,156,156,156,
                157,158,158,160,160,160,160,160,161,161,161,161,162,
                163,163,164,164,164,165,166,167,168,168,169,170,172,
                173]

dados_altura = np.array(dados_altura)

In [3]:
dados = dados_altura

### Media Aritmetica Simples

In [4]:
dados_altura.sum() / len(dados_altura)

160.375

In [5]:
dados_altura.mean()

160.375

In [6]:
#retorna valor inteiro
statistics.mean(dados_altura)

160

### Moda

In [7]:
statistics.mode(dados_altura)

160

In [8]:
stats.mode(dados_altura)

ModeResult(mode=160, count=5)

In [9]:
#Calculo manual(impar)


In [10]:
#Calculo manual (par)


### Mediana

- IMPAR

In [11]:
dados_impar = [150, 151, 152, 152, 153, 154, 155, 155, 155]

In [12]:
posicao = len(dados_impar) // 2
posicao

4

In [13]:
posicao = math.ceil(posicao)
posicao

4

In [14]:
dados_impar[posicao]

153

- PAR

In [15]:
posicao = len(dados_altura) // 2
posicao

20

In [16]:
dados[posicao -1 ], dados[posicao]

(160, 160)

In [17]:
mediana = (dados[posicao - 1] + dados[posicao] ) / 2
mediana

160.0

In [18]:
#Biblioteca np
np.median(dados_altura) , np.median(dados_impar)

(160.0, 153.0)

In [19]:
#Biblioteca statistics
statistics.median(dados_altura), statistics.median(dados_impar)

(160.0, 153)

### Media Aritmetica Ponderada

In [20]:
notas = np.array([9, 8, 7, 3])
pesos = np.array([1, 2, 3, 4])

In [21]:
(9*1 + 8*2 + 7*3 + 3*4) / (1 +2 +3 +4)

5.8

In [22]:
media_ponderada = (notas * pesos).sum() / pesos.sum()
media_ponderada

5.8

In [23]:
np.average(notas, weights=pesos)

5.8

### Dados Agrupados Media Aritmetica, Moda, Mediana

In [24]:
dados = {'inferior': [150, 154,158, 162, 166, 170],
         'superior': [154, 158, 162, 166, 170, 174],
         'fi': [5, 9, 11, 7, 5, 3]}

In [25]:
dataset = pd.DataFrame(dados)
dataset

inferior  superior  fi
0       150       154   5
1       154       158   9
2       158       162  11
3       162       166   7
4       166       170   5
5       170       174   3

In [26]:
dataset['xi'] = (dataset['superior'] + dataset['inferior']) / 2
dataset

inferior  superior  fi     xi
0       150       154   5  152.0
1       154       158   9  156.0
2       158       162  11  160.0
3       162       166   7  164.0
4       166       170   5  168.0
5       170       174   3  172.0

In [27]:
dataset['fi.xi'] = dataset['fi'] * dataset['xi']
dataset

inferior  superior  fi     xi   fi.xi
0       150       154   5  152.0   760.0
1       154       158   9  156.0  1404.0
2       158       162  11  160.0  1760.0
3       162       166   7  164.0  1148.0
4       166       170   5  168.0   840.0
5       170       174   3  172.0   516.0

In [28]:
dataset['Fi'] = 0
dataset

inferior  superior  fi     xi   fi.xi  Fi
0       150       154   5  152.0   760.0   0
1       154       158   9  156.0  1404.0   0
2       158       162  11  160.0  1760.0   0
3       162       166   7  164.0  1148.0   0
4       166       170   5  168.0   840.0   0
5       170       174   3  172.0   516.0   0

In [29]:
frequencia_acumulada = []
somatorio = 0
for linha in dataset.iterrows():
  #print(linha[1])
  #print(linha[1][2])
  somatorio += linha[1][2]
  frequencia_acumulada.append(somatorio)

frequencia_acumulada

[5.0, 14.0, 25.0, 32.0, 37.0, 40.0]

In [30]:
dataset['Fi'] = frequencia_acumulada
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

#### Media

In [31]:
dataset['fi'].sum(), dataset['fi.xi'].sum()

(40, 6428.0)

In [32]:
dataset['fi.xi'].sum() / dataset['fi'].sum()

160.7

#### Moda

In [33]:
dataset['fi'].max()

11

In [34]:
dataset[dataset['fi'] == dataset['fi'].max()]

inferior  superior  fi     xi   fi.xi    Fi
2       158       162  11  160.0  1760.0  25.0

In [35]:
dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

160.0

#### Mediana

In [36]:
fi_2 = dataset['fi'].sum() / 2

In [37]:
limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0,
for linha in dataset.iterrows():
  #print(linha)
  limite_inferior = linha[1][0]
  frequencia_classe = linha[1][2]
  id_frequencia_anterior = linha[0]
  if linha[1][5] >= fi_2:
    id_frequencia_anterior -= 1
    break

In [38]:
limite_inferior, frequencia_classe, id_frequencia_anterior

(158.0, 11.0, 1)

In [39]:
Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['fi'].values[0]
Fi_anterior

9

In [40]:
mediana = limite_inferior + ((fi_2 - Fi_anterior) * 4 ) / frequencia_classe
mediana

162.0

In [41]:
def get_estatisticas(dataframe):
  media = dataset['fi.xi'].sum() / dataset['fi'].sum()
  moda = dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

  fi_2 = dataset['fi'].sum() / 2

  limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0
  for linha in dataset.iterrows():
  #print(linha)
    limite_inferior = linha[1][0]
    frequencia_classe = linha[1][2]
    id_frequencia_anterior = linha[0]
    if linha[1][5] >= fi_2:
      id_frequencia_anterior -= 1
      break
  Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['fi'].values[0]
  mediana = limite_inferior + ((fi_2 - Fi_anterior) * 4 ) / frequencia_classe

  return media, moda, mediana

In [42]:
get_estatisticas(dataset)
# FIM aula 54, mas meu resultado deu diferente. Averiguar o que aconteceu

(160.7, 160.0, 162.0)

### Media Geometrica, Harmonica e Quadratica

#### Geometrica

In [43]:
dados_altura

array([150, 151, 152, 152, 153, 154, 155, 155, 155, 155, 156, 156, 156,
       157, 158, 158, 160, 160, 160, 160, 160, 161, 161, 161, 161, 162,
       163, 163, 164, 164, 164, 165, 166, 167, 168, 168, 169, 170, 172,
       173])

In [44]:
from scipy.stats.mstats import gmean, hmean

In [45]:
gmean(dados_altura)

160.26958390038905

#### Harmonica

In [46]:
hmean(dados_altura)

160.1647194799467

In [47]:
def quadratic_mean(dados):
  return math.sqrt(sum(n * n for n in dados) / len(dados))

In [48]:
quadratic_mean(dados_altura)

160.48091786876097

### Quartis

#### Nao agrupados

In [49]:
dados_impar

[150, 151, 152, 152, 153, 154, 155, 155, 155]

In [50]:
#Calculo manual
np.median(dados_impar)

153.0

In [51]:
posicao_mediana = math.floor(len(dados_impar) / 2 )
posicao_mediana

4

In [52]:
esquerda = dados_impar[0 : posicao_mediana]
direita = dados_impar[posicao_mediana + 1: ]
esquerda, direita

([150, 151, 152, 152], [154, 155, 155, 155])

In [53]:
np.median(esquerda), np.median(direita)

(151.5, 155.0)

In [54]:
#Numpy | 0.75 efine que queremos o 3 QUARTIL | ele inclui a mediana
np.quantile(dados_impar, 0.75)

155.0

In [55]:
np.quantile(dados_altura, 0.25), np.quantile(dados_altura, 0.50), np.quantile(dados_altura, 0.75)

(155.75, 160.0, 164.0)

In [56]:
#scipy
stats.scoreatpercentile(dados_altura, 25), stats.scoreatpercentile(dados_altura, 50), stats.scoreatpercentile(dados_altura, 75)

(155.75, 160.0, 164.0)

In [57]:
#pandas
dataset_altura = pd.DataFrame(dados_altura)
dataset_altura.head(3)

0
0  150
1  151
2  152

In [58]:
dataset_altura.quantile([0.25, 0.50, 0.75])

0
0.25  155.75
0.50  160.00
0.75  164.00

In [59]:
dataset_altura.describe()

0
count   40.000000
mean   160.375000
std      5.903877
min    150.000000
25%    155.750000
50%    160.000000
75%    164.000000
max    173.000000

#### Agrupado

In [60]:
def get_quantil(dataset, q1 = True):
  if q1 == True:
    fi_4 = dataset['fi'].sum() / 4
  else:
    fi_4 = ( 3 * dataset['fi'].sum()) / 4


  limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0
  for linha in dataset.iterrows():
  #print(linha)
    limite_inferior = linha[1][0]
    frequencia_classe = linha[1][2]
    id_frequencia_anterior = linha[0]
    if linha[1][5] >= fi_4:
      id_frequencia_anterior -= 1
      break
  Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['fi'].values[0]
  q = limite_inferior + ((fi_4 - Fi_anterior) * 4 ) / frequencia_classe

  return q

In [61]:
get_quantil(dataset), get_quantil(dataset, q1 = False)  #q1 = False devia ser = 164.85aviriguar dps

(156.22222222222223, 172.85714285714286)

### Percentis

In [62]:
np.median(dataset_altura)

160.0

In [63]:
np.quantile(dataset_altura, 0.5)

160.0

In [64]:
np.percentile(dataset_altura, 50)

160.0

In [65]:
# Mediana de 5% eh, Mediana de 10% eh, Mediana de 90% eh
np.percentile(dataset_altura, 5), np.percentile(dataset_altura, 10), np.percentile(dataset_altura, 80),


(151.95, 152.9, 165.2)

In [66]:
stats.scoreatpercentile(dataset_altura, 5), stats.scoreatpercentile(dataset_altura,10)

(151.95000000000002, 152.89999999999998)

In [67]:
dataset_altura.head(3)

0
0  150
1  151
2  152

In [68]:
dataset_altura.quantile([0.05, 0.10, 0.90])

0
0.05  151.95
0.10  152.90
0.90  168.10

### Medidas de dispersao aula 63

- Amplitude quica

In [69]:
dados_altura.max() - dados_altura.min()

23

In [70]:
q1 = np.quantile(dados_altura,0.25)
q3 = np.quantile(dados_altura,0.75)
q1, q3

(155.75, 164.0)

In [71]:
diferenca_interquartil = q3 -q1
diferenca_interquartil

8.25

In [72]:
inferior = q1 - (1.5 * diferenca_interquartil)
print(f"Limite inferior : {inferior}")
print(f"Diferenca entre limite inferior e outlier: {dados_altura[0] - inferior}")

Limite inferior : 143.375
Diferenca entre limite inferior e outlier: 6.625


In [73]:
superior = q3 + (1.5 * diferenca_interquartil)
print(f"Limite superior : {superior}")
print(f"Diferenca entre limite inferior e outlier: {superior - dados_altura[-1]}")

Limite superior : 176.375
Diferenca entre limite inferior e outlier: 3.375


In [74]:
n = 11

In [75]:
ponto_medio = n // 2
ponto_medio

5

### Variancia

In [76]:
dados_impar = np.array(dados_impar)

In [77]:
#calculo manual
def variancia(dados_impar):
  media = dados_impar.sum() / len(dados_impar)
  desvio = abs(dados_impar - media) #Como eh um array, a subtracao diminui cada valor do array pelo valor fornecido
  desvio = desvio * desvio
  soma_desvio = desvio.sum()
  variancia = soma_desvio / len(dados_impar)
  return variancia

variancia(dados_impar)

3.111111111111111

In [78]:
#Numpy
np.var(dados_impar), np.var(dados_altura)

(3.111111111111111, 33.984375)

In [79]:
#statistics
statistics.variance(dados_altura)

34

In [80]:
from scipy import ndimage
ndimage.variance(dados_altura)

33.984375

### Desvio Padrao

#### Desvio Padrao com dados NAO agrupados

In [81]:
desvio_padrao = math.sqrt(np.var(dados_impar))
desvio_padrao

1.7638342073763937

In [82]:
np.std(dados_impar), np.std(dados_altura)

(1.7638342073763937, 5.829611908180509)

In [83]:
statistics.stdev(dados_altura)

5.830951894845301

In [84]:
stats.tstd(dados_altura, ddof=0) #ddof = degraus de liberdade, default eh 1, precisamos de 0. ddof=1(para amostras), ddof=0(para populacoes)

5.829611908180509

In [85]:
#calculo manual
def variancia_desvio_padrao(dados_impar):
  media = dados_impar.sum() / len(dados_impar)
  desvio = abs(dados_impar - media) #Como eh um array, a subtracao diminui cada valor do array pelo valor fornecido
  desvio = desvio * desvio
  soma_desvio = desvio.sum()
  variancia = soma_desvio / len(dados_impar)
  return variancia, math.sqrt(variancia)

variancia_desvio_padrao(dados_impar)

(3.111111111111111, 1.7638342073763937)

#### Desvio com dados Agrupados

In [86]:
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [87]:
dataset['xi_2'] = dataset['xi'] ** 2
dataset['xi_2']

0    23104.0
1    24336.0
2    25600.0
3    26896.0
4    28224.0
5    29584.0
Name: xi_2, dtype: float64

In [88]:
dataset['fi_xi_2'] = dataset['fi'] * dataset['xi_2']
dataset['fi_xi_2']

0    115520.0
1    219024.0
2    281600.0
3    188272.0
4    141120.0
5     88752.0
Name: fi_xi_2, dtype: float64

In [89]:
dp = math.sqrt((dataset['fi_xi_2'].sum() / dataset['fi'].sum()) - (dataset['fi.xi'].sum() / dataset['fi'].sum())**2 )
dp

5.719265687131764

### Coeficinete de Variacao

In [90]:
cv = (desvio_padrao / dados_impar.mean()) * 100
cv

1.1528328152786886

In [91]:
#calculo manual
def variancia_desvio_padrao_coeficiente(dados_impar):
  media = dados_impar.sum() / len(dados_impar)
  desvio = abs(dados_impar - media) #Como eh um array, a subtracao diminui cada valor do array pelo valor fornecido
  desvio = desvio * desvio
  soma_desvio = desvio.sum()
  variancia = soma_desvio / len(dados_impar)
  dp = math.sqrt(variancia)
  cv = (dp / media) * 100
  return variancia, dp, cv

variancia_desvio_padrao_coeficiente(dados_impar)

(3.111111111111111, 1.7638342073763937, 1.1528328152786886)

In [92]:
stats.variation(dados_impar) * 100

1.1528328152786886

In [93]:
stats.variation(dados_altura) * 100

3.634987939629312

In [94]:
# Variacia, desvio padrao, coeficiente de variacao, para comparar duas ou mais bases de dados

### Avaliação de Algoritmos de Machine Learn

In [138]:

ml = pd.read_csv('/content/drive/MyDrive/curso_estatistica/estatistica/Bases de dados/credit_data.csv') # passar para github depois

In [140]:
credit =ml

In [96]:
ml.dropna(inplace=True)

In [97]:
ml.head(3), ml.shape

(   i#clientid        income        age         loan  c#default
 0           1  66155.925095  59.017015  8106.532131          0
 1           2  34415.153966  48.117153  6564.745018          0
 2           3  57317.170063  63.108049  8020.953296          0,
 (1997, 5))

In [98]:
X = ml.iloc[:, 1:4].values #.values para pegar apenas os valores e nao a estrutura do dataframe
y = ml.iloc[:, 4].values

In [99]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


In [100]:
resultadoNB = []
resultadoLR = []
resultadoRF = []

for i in range(30):
  X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.2,
                                                                    stratify = y, random_state = i)
  nb = GaussianNB()
  nb.fit(X_treinamento, y_treinamento)
  resultadoNB.append(accuracy_score(y_teste, nb.predict(X_teste)))

  lf = LogisticRegression()
  lf.fit(X_treinamento, y_treinamento)
  resultadoLR.append(accuracy_score(y_teste, lf.predict(X_teste)))

  rf = RandomForestClassifier()
  rf.fit(X_treinamento, y_treinamento)
  resultadoRF.append(accuracy_score(y_teste, rf.predict(X_teste)))

In [101]:
print(resultadoNB)

[0.925, 0.925, 0.9325, 0.925, 0.92, 0.905, 0.9175, 0.9175, 0.9125, 0.9325, 0.9225, 0.9125, 0.935, 0.9175, 0.925, 0.9175, 0.9275, 0.92, 0.9325, 0.92, 0.93, 0.905, 0.9175, 0.9325, 0.9425, 0.9375, 0.94, 0.92, 0.935, 0.925]


In [102]:
print(resultadoLR)


[0.9325, 0.91, 0.9125, 0.9225, 0.9075, 0.89, 0.91, 0.9075, 0.8775, 0.915, 0.9175, 0.9, 0.925, 0.9175, 0.9025, 0.9125, 0.9525, 0.91, 0.9225, 0.9075, 0.925, 0.905, 0.9075, 0.945, 0.9225, 0.9275, 0.9225, 0.9175, 0.91, 0.9]


In [103]:
print(resultadoRF)


[0.975, 0.9875, 0.9775, 0.9925, 0.9775, 0.9825, 0.985, 0.9875, 0.9775, 0.99, 0.9825, 0.98, 0.9725, 0.985, 0.9825, 0.975, 0.9875, 0.9775, 0.99, 0.9825, 0.9825, 0.98, 0.975, 0.985, 0.9875, 0.995, 0.9925, 0.9825, 0.9925, 0.985]


In [104]:
resultadoNB = np.array(resultadoNB)
resultadoLR = np.array(resultadoLR)
resultadoRF = np.array(resultadoRF)

####Media dos classificadores

In [105]:
print(f"""Media do Naive Bayes: {resultadoNB.mean():.4f},
\nMedia do Logistic Regresion: {resultadoLR.mean():.4f},
\nMedia do Random Florest: {resultadoRF.mean():.4f}""")

Media do Naive Bayes: 0.9243,

Media do Logistic Regresion: 0.9145,

Media do Random Florest: 0.9835


#### Moda dos classificadores

In [106]:
modanb = stats.mode(resultadoNB)
modalr = stats.mode(resultadoLR)
modarf = stats.mode(resultadoRF)

print(f"""Moda do Naive Bayes: {modanb}
\nModa do Logistic Regresion: {modalr}
\nModa do Random Florest: {modarf}""")

Moda do Naive Bayes: ModeResult(mode=0.9175, count=5)

Moda do Logistic Regresion: ModeResult(mode=0.9075, count=4)

Moda do Random Florest: ModeResult(mode=0.9825, count=6)


#### Mediana

In [107]:
print(f"""Mediana do Naive Bayes: {np.median(resultadoNB)}
\nMediana do Logistic Regresion: {np.median(resultadoLR)}
\nMediana do Random Florest: {np.median(resultadoRF)}""")

Mediana do Naive Bayes: 0.925

Mediana do Logistic Regresion: 0.9125

Mediana do Random Florest: 0.9825


#### Variancia

In [108]:
np.set_printoptions(suppress=True)

In [109]:
varnb = np.var(resultadoNB, ddof=0)
varlr = np.var(resultadoLR, ddof=0)
varrf = np.var(resultadoRF, ddof=0)

print(f"""Variancia do Naive Bayes: {varnb}
\nVariancia do Logistic Regresion: {varlr}
\nVariancia do Random Florest: {varrf}""")

Variancia do Naive Bayes: 8.756250000000001e-05

Variancia do Logistic Regresion: 0.00020933333333333337

Variancia do Random Florest: 3.483333333333341e-05


In [110]:
np.min([varnb, varlr, varrf])

3.483333333333341e-05

In [111]:
np.max([varnb, varlr, varrf])


0.00020933333333333337

#### Desvio Padrao

In [112]:
dpnb = np.std(resultadoNB)
dplr = np.std(resultadoLR)
dprf = np.std(resultadoRF)

print(f"""Desvio padrao do Naive Bayes: {dpnb}
\nDesvio padrao do Logistic Regresion: {dplr}
\nDesvio padrao do Random Florest: {dprf}""")

Desvio padrao do Naive Bayes: 0.00935748363610645

Desvio padrao do Logistic Regresion: 0.014468356276140472

Desvio padrao do Random Florest: 0.0059019770698752645


In [113]:
resultadoLR

array([0.9325, 0.91  , 0.9125, 0.9225, 0.9075, 0.89  , 0.91  , 0.9075,
       0.8775, 0.915 , 0.9175, 0.9   , 0.925 , 0.9175, 0.9025, 0.9125,
       0.9525, 0.91  , 0.9225, 0.9075, 0.925 , 0.905 , 0.9075, 0.945 ,
       0.9225, 0.9275, 0.9225, 0.9175, 0.91  , 0.9   ])

In [114]:
resultadoNB

array([0.925 , 0.925 , 0.9325, 0.925 , 0.92  , 0.905 , 0.9175, 0.9175,
       0.9125, 0.9325, 0.9225, 0.9125, 0.935 , 0.9175, 0.925 , 0.9175,
       0.9275, 0.92  , 0.9325, 0.92  , 0.93  , 0.905 , 0.9175, 0.9325,
       0.9425, 0.9375, 0.94  , 0.92  , 0.935 , 0.925 ])

#### Coeficiente de variacao

In [115]:
coefnb = stats.variation(resultadoNB) * 100
coeflr = stats.variation(resultadoLR) * 100
coefrf = stats.variation(resultadoRF) * 100

print(f"""Coeficiente de Variacao do Naive Bayes: {coefnb}
\nCoeficiente de Variacao do Logistic Regresion: {coeflr}
\nCoeficiente de Variacao  do Random Florest: {coefrf}""")

Coeficiente de Variacao do Naive Bayes: 1.0124407504578252

Coeficiente de Variacao do Logistic Regresion: 1.5821056616884057

Coeficiente de Variacao  do Random Florest: 0.6000993461998235


In [116]:
dataset

inferior  superior  fi     xi   fi.xi    Fi     xi_2   fi_xi_2
0       150       154   5  152.0   760.0   5.0  23104.0  115520.0
1       154       158   9  156.0  1404.0  14.0  24336.0  219024.0
2       158       162  11  160.0  1760.0  25.0  25600.0  281600.0
3       162       166   7  164.0  1148.0  32.0  26896.0  188272.0
4       166       170   5  168.0   840.0  37.0  28224.0  141120.0
5       170       174   3  172.0   516.0  40.0  29584.0   88752.0

#### Solucao professor


In [117]:
from sklearn.model_selection import KFold, cross_val_score

In [118]:
resultadoNBcv = []
resultadoLRcv = []
resultadoRFcv = []

for i in range(30):
  kfold = KFold(n_splits=10, shuffle = True, random_state = i)

  nb = GaussianNB()
  scores = cross_val_score(nb, X, y, cv=kfold)
  resultadoNBcv.append(scores.mean())

  lr = LogisticRegression()
  scores = cross_val_score(lr, X, y, cv=kfold)
  resultadoLRcv.append(scores.mean())

  rf = RandomForestClassifier()
  scores = cross_val_score(rf, X, y, cv=kfold)
  resultadoRFcv.append(scores.mean())

In [119]:
print(resultadoNBcv)

[0.9248618090452261, 0.9249170854271356, 0.9248894472361808, 0.9228819095477387, 0.9248718592964824, 0.9253894472361809, 0.9243844221105528, 0.9248894472361808, 0.9248718592964824, 0.9238894472361808, 0.9253844221105527, 0.9244020100502512, 0.9253743718592965, 0.924394472361809, 0.9253869346733667, 0.9248819095477387, 0.9258844221105527, 0.924894472361809, 0.9238819095477387, 0.9258844221105529, 0.9258944723618091, 0.9253894472361811, 0.92436432160804, 0.9263844221105527, 0.9228944723618092, 0.9253894472361809, 0.9248869346733668, 0.9253919597989949, 0.9253819095477386, 0.9258844221105527]


In [120]:
print(resultadoLRcv)

[0.9113718592964826, 0.9103668341708543, 0.918359296482412, 0.9158768844221106, 0.9133417085427136, 0.9108718592964824, 0.9188366834170856, 0.9188969849246231, 0.913356783919598, 0.9148693467336683, 0.9098718592964824, 0.9183542713567838, 0.9183793969849248, 0.9213618090452261, 0.9098643216080402, 0.914356783919598, 0.9103693467336684, 0.915856783919598, 0.9128542713567839, 0.9123668341708543, 0.9208944723618091, 0.9108668341708542, 0.9103467336683417, 0.9133768844221105, 0.9098592964824121, 0.9148768844221105, 0.910859296482412, 0.9113768844221104, 0.9113668341708543, 0.9098442211055277]


In [121]:
print(resultadoRFcv)

[0.9864723618090453, 0.9864849246231155, 0.9864798994974875, 0.9859623115577889, 0.9889798994974874, 0.9854824120603016, 0.9874723618090453, 0.9874874371859296, 0.9889849246231156, 0.9869849246231155, 0.9884773869346735, 0.9864748743718593, 0.9874773869346735, 0.9894824120603015, 0.9874874371859296, 0.9894824120603015, 0.9879849246231156, 0.9874698492462313, 0.9834723618090452, 0.9864849246231155, 0.9869824120603015, 0.9864773869346735, 0.9844824120603015, 0.9889798994974874, 0.9859773869346734, 0.9874899497487437, 0.9854773869346733, 0.9879798994974875, 0.9899924623115577, 0.9884874371859297]


In [122]:
stats.variation(resultadoNBcv) * 100, stats.variation(resultadoLRcv) * 100, stats.variation(resultadoRFcv) * 100

(0.08641071566366061, 0.38801026116292653, 0.15034922336467685)

### Selecao de atributos utilizando variancia

In [123]:
np.random.rand(50)# 50 valores de 0.0 a 1.0

array([0.78672101, 0.64971114, 0.2375461 , 0.43534091, 0.93102162,
       0.15288855, 0.96237009, 0.60720459, 0.18421732, 0.3558669 ,
       0.48250043, 0.85846229, 0.23255815, 0.75002889, 0.55301346,
       0.50590674, 0.45310325, 0.91027338, 0.34068847, 0.97133143,
       0.27187051, 0.83283729, 0.39200007, 0.43664736, 0.5357543 ,
       0.41947231, 0.78214948, 0.18199554, 0.34602443, 0.82452538,
       0.6001552 , 0.10636052, 0.54911912, 0.83668862, 0.65631635,
       0.0605054 , 0.0212686 , 0.63529234, 0.85315701, 0.04606874,
       0.68231006, 0.29363799, 0.39165496, 0.5037019 , 0.86513261,
       0.7953139 , 0.12130633, 0.63798171, 0.86808179, 0.93986021])

In [124]:
np.random.randint(0, 2) #0 a 1

0

In [125]:
base_selecao = {'a' : np.random.rand(20),
                'b' : np.array([0.5] * 20),
                'classe' : np.random.randint(0, 2, size= 20)
                }

base_selecao

{'a': array([0.66797601, 0.10751854, 0.61201334, 0.45115964, 0.69204431,
        0.0680649 , 0.6839206 , 0.04814369, 0.92145617, 0.17074216,
        0.97156131, 0.26999633, 0.81407665, 0.42018487, 0.34606163,
        0.05452728, 0.73621497, 0.74743022, 0.26456783, 0.13786622]),
 'b': array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]),
 'classe': array([1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0])}

In [126]:
fic = pd.DataFrame(base_selecao)
fic.head()

a    b  classe
0  0.667976  0.5       1
1  0.107519  0.5       0
2  0.612013  0.5       1
3  0.451160  0.5       0
4  0.692044  0.5       1

In [127]:
fic.describe()

a     b     classe
count  20.000000  20.0  20.000000
mean    0.459276   0.5   0.600000
std     0.309288   0.0   0.502625
min     0.048144   0.5   0.000000
25%     0.162523   0.5   0.000000
50%     0.435672   0.5   1.000000
75%     0.703087   0.5   1.000000
max     0.971561   0.5   1.000000

In [128]:
math.sqrt(np.var(fic['a']))

0.30145690237512374

In [129]:
np.var(fic['a']), np.var(fic['b'])

(0.0908762639896049, 0.0)

In [130]:
X = fic.iloc[:, 0:2].values #Assim para no formato array
X

array([[0.66797601, 0.5       ],
       [0.10751854, 0.5       ],
       [0.61201334, 0.5       ],
       [0.45115964, 0.5       ],
       [0.69204431, 0.5       ],
       [0.0680649 , 0.5       ],
       [0.6839206 , 0.5       ],
       [0.04814369, 0.5       ],
       [0.92145617, 0.5       ],
       [0.17074216, 0.5       ],
       [0.97156131, 0.5       ],
       [0.26999633, 0.5       ],
       [0.81407665, 0.5       ],
       [0.42018487, 0.5       ],
       [0.34606163, 0.5       ],
       [0.05452728, 0.5       ],
       [0.73621497, 0.5       ],
       [0.74743022, 0.5       ],
       [0.26456783, 0.5       ],
       [0.13786622, 0.5       ]])

In [131]:
from sklearn.feature_selection import VarianceThreshold

In [132]:
selecao = VarianceThreshold(threshold=0.07)

X_novo = selecao.fit_transform(X)
X_novo, X_novo.shape

(array([[0.66797601],
        [0.10751854],
        [0.61201334],
        [0.45115964],
        [0.69204431],
        [0.0680649 ],
        [0.6839206 ],
        [0.04814369],
        [0.92145617],
        [0.17074216],
        [0.97156131],
        [0.26999633],
        [0.81407665],
        [0.42018487],
        [0.34606163],
        [0.05452728],
        [0.73621497],
        [0.74743022],
        [0.26456783],
        [0.13786622]]),
 (20, 1))

In [133]:
selecao.variances_

array([0.09087626, 0.        ])

In [134]:
indices = np.where(selecao.variances_ > 0.07)
indices

(array([0]),)

In [143]:
credit.isnull().sum()

i#clientid    0
income        0
age           3
loan          0
c#default     0
dtype: int64

In [144]:
nulos = credit[credit.isnull().any(axis=1)] #axis=1 para ele pegar todas as linhas
nulos

i#clientid        income  age         loan  c#default
28          29  59417.805406  NaN  2082.625938          0
30          31  48528.852796  NaN  6155.784670          0
31          32  23526.302555  NaN  2862.010139          0

In [148]:
credit['age'].mean(), credit['age'].median()

(40.80755937840458, 41.3171591130085)

In [150]:
credit['age'] = credit['age'].replace(to_replace = np.nan, value = credit['age'].mean())

In [151]:
credit[credit.isnull().any(axis=1)] #axis=1 para ele pegar todas as linhas


Empty DataFrame
Columns: [i#clientid, income, age, loan, c#default]
Index: []

In [156]:
autos = pd.read_csv('/content/drive/MyDrive/curso_estatistica/estatistica/Bases de dados/autos.csv', encoding='ISO-8859-1')
autos

In [158]:
autos.head()

dateCrawled                            name  seller offerType  \
0  2016-03-24 11:52:17                      Golf_3_1.6  privat   Angebot   
1  2016-03-24 10:58:45            A5_Sportback_2.7_Tdi  privat   Angebot   
2  2016-03-14 12:52:21  Jeep_Grand_Cherokee_"Overland"  privat   Angebot   
3  2016-03-17 16:54:04              GOLF_4_1_4__3TÜRER  privat   Angebot   
4  2016-03-31 17:25:20  Skoda_Fabia_1.4_TDI_PD_Classic  privat   Angebot   

   price abtest vehicleType  yearOfRegistration    gearbox  powerPS  model  \
0    480   test         NaN                1993    manuell        0   golf   
1  18300   test       coupe                2011    manuell      190    NaN   
2   9800   test         suv                2004  automatik      163  grand   
3   1500   test  kleinwagen                2001    manuell       75   golf   
4   3600   test  kleinwagen                2008    manuell       69  fabia   

   kilometer  monthOfRegistration fuelType       brand notRepairedDamage  \
0     150000                    0   benzin  volkswagen               NaN   
1     125000                    5   diesel        audi                ja   
2     125000                    8   diesel        jeep               NaN   
3     150000                    6   benzin  volkswagen              nein   
4      90000                    7   diesel       skoda              nein   

           dateCreated  nrOfPictures  postalCode             lastSeen  
0  2016-03-24 00:00:00             0       70435  2016-04-07 03:16:57  
1  2016-03-24 00:00:00             0       66954  2016-04-07 01:46:50  
2  2016-03-14 00:00:00             0       90480  2016-04-05 12:47:46  
3  2016-03-17 00:00:00             0       91074  2016-03-17 17:40:17  
4  2016-03-31 00:00:00             0       60437  2016-04-06 10:17:21

In [159]:
autos.isnull().sum()

dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [160]:
autos['fuelType'].unique()

array(['benzin', 'diesel', nan, 'lpg', 'andere', 'hybrid', 'cng',
       'elektro'], dtype=object)

In [164]:
statistics.mode(autos['fuelType'])

'benzin'

In [165]:
autos['fuelType'] = autos['fuelType'].replace(to_replace=np.nan, value=statistics.mode(autos['fuelType']))

In [166]:
autos['fuelType'].unique()

array(['benzin', 'diesel', 'lpg', 'andere', 'hybrid', 'cng', 'elektro'],
      dtype=object)